waypoints:
    - point:
        x: -2.45785
        y: -4.23491
        z: 0
        function: run
    - point:
        x: -0.418372
        y: -1.64567
        z: 3.8147e-06
        function: run
    - point:
        x: -0.289962
        y: 13.6507
        z: 0
        function: run
    - point:
        x: -0.192162
        y: 28.0174
        z: 0
        function: run
    - point:
        x: -2.05747
        y: 29.8908
        z: 1.90735e-06
        function: run
    - point:
        x: -7.89951
        y: 29.9157
        z: 1.90735e-06
        function: run
    - point:
        x: -9.81636
        y: 28.0095
        z: 1.90735e-06
        function: run
    - point:
        x: -9.76497
        y: 13.1511
        z: 1.90735e-06
        function: run
    - point:
        x: -9.91886
        y: -1.40668
        z: 5.72205e-06
        function: run
    - point:
        x: -7.71031
        y: -4.22006
        z: 3.8147e-06
        function: run
    - point:
        x: -4.96514
        y: -4.20082
        z: 3.8147e-06
        function: suspend
